title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 You can update description in update blog details page.

baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://bpmottathai.github.io/justy" # the base hostname & protocol for your site
adsense_id: ca-pub-0000000000000000

markdown: kramdown

name: Your awesome title

date: 2019-01-24 19:50:18 +0000
permalink: /:year/:month/:day/:title

logo: false
sass:
    load_paths:
        - _sass
        - bs
paginate: 10
adsid: ca-pub-8582082279264878
domain_name: https://bpmottathai.github.io/justy/
google_analytics: UA-31XXXXXX-X


gems:
  - jekyll-paginate
  - jekyll-sitemap
cover: test2
author_image: 
# Details for the RSS feed generator
author:        justy
